### ISSUE TITLE
What constitutes a problem statement

### ISSUE THREAD

**Issue by enkiluv** [ch33233/SWE-Parking_Booking#1]
Problem Statement는 프로젝트를 의뢰하는 고객이 제시하는 것이므로 고객의 입장에서 작성해야 합니다.  "..할 예정이다" 혹은 "..할 수 있다"와 같은 문장은 개발자의 의도를 말하는 것으로 problem statement에 포함되어서는 안됩니다.  전반적으로 "..할 필요가 있다", "..해야한다"와 같은 표현으로 구성되어야 합니다.

**Comment by Kapurichino** [comment]
감사합니다. Issue 반영하여 수정하였습니다.

**Comment by enkiluv** [comment]
사소한 차이지만 고객의 관점에서 문제를 본다는 것은 많은 훈련이 필요합니다. 좋은 경험이 되었기를 바랍니다.
