### ISSUE TITLE
빠른 예약 기능 추가

### ISSUE THREAD

**Issue by SeoHyunJong** [ch33233/SWE-Parking_Booking#2]
안녕하세요? 오늘 Zoom 강의에서 교수님의 말씀을 토대로 고객의 관점에서 기능에 대한 이슈를 올립니다.

어플리케이션을 사용하는 고객의 상황을 생각해보았을때 집이나 회사에서 주차장 지도를 열고 미리 예약하는 경우도 있겠지만
도로 위에서 잠시 정차하거나 신호등을 기다리는 상황에서 빨리 주차할 수 있는 곳을 찾는 상황이 많을 것입니다.
예시로 카카오 택시를 사용하는 대부분의 이용자는 길가에서 빠르게 택시를 찾을 때 이용합니다.

하지만 현재 구상한 어플리케이션 기능으로는 이러한 고객의 요구를 만족시키기 어려운 것 같습니다.
예약하기 버튼 -> 지도 드래그 -> 주차장 내부구성도에서 slot 선택 -> 시간, 날짜 선택 -> 결제

과정이 긴 것도 문제이지만 특히, slot 선택 후 시간과 날짜를 선택하는 과정에서 원하는 시간과 날짜를 예약하지 못한 경우
다시 다른 slot으로 넘어가 해당 시간을 찾는 수고로움이 필요합니다. 또한 매 예약마다 결제 정보를 입력하는 것도 시간이 꽤 소요됩니다.

따라서 이 과정을 간소화 한 빠른 예약 기능을 추가하는게 어떠한지 팀원 여러분께 건의하고 싶습니다.
이와 같은 기능을 고객의 관점에서 다시 Problem placement 에 반영해보는게 어떠할까요?
(교수님의 평가 기준에 깃허브에 나타난 팀워크가 중요시 되므로 카카오톡 보다는 이곳 깃허브 이슈에서 토론하고 싶습니다.)

제가 임시로 구상한 빠른 예약 기능은 사용자의 결제 정보를 사전에 어플리케이션에서 저장하고
고객은 단지 주차장의 위치와 원하는 시간만을 입력하는 것입니다.
이를 토대로 어플리케이션이 자동으로 slot을 선택하고 결제를 진행하면 좋을 것 같습니다.

**Comment by kjh99660** [comment]
이런 건의 사항을보면 상황 제한을 확실히 하는게 중요하다고 생각합니다.

저번에 회의 중에 많은 문제를 주차장 안쪽에 카메라가 설치되어 있다는 가정으로 해결했던거 같은데 만약 모든 주차장을 탐색할 수 있다고 가정한다면 추가하기로 한 기능들 중 몇 가지를 사용 못하게될 수 있습니다. 

따라서 기능을 추가하기 앞서 저희가 정한 고객의 요구를 확실하게 고정하고 넘어갔으면 좋겠습니다.

**Comment by SeoHyunJong** [comment]
응답해주셔서 감사합니다. :)
우선 모든 주차장을 탐색할 수 있다는 가정이 아니었습니다. 제 글이 명확하지 않은 것 같아 죄송하다는 말씀 드립니다.
저는 슬롯 선택에서 예약 기능까지를 자동화하는 기능을 말하는 것이었습니다.
주차장을 선택하는건 기존과 동일합니다. 주차장은 개인 주차장 하나여도 괜찮습니다. :)
큰 틀에서 보자면 새로운 기능 보다는 기존의 예약하기 기능에서 몇개를 자동화한 것입니다.

**Comment by hajeehoon** [comment]
현종님이 말씀하신 내용이 근처의 주차장을 선택할 수 있는 기능에 중점을 둔 것이 아니라 메인 화면에서 간편하게 예약 가능한
버튼의 간소화를 말씀하시는 것 같네요. Client의 요구사항중에 예약 버튼의 간소화가 추가되거나 이를 별도로 원한다면 
반영할만한 의견인것 같습니다.

**Comment by Kapurichino** [comment]
고객이 이 서비스를 이용하는 상황이 어떠한지를 보아야하는 것 같습니다. 그리고 저희가 구상한 The Problem에서 고객이 처한 상황은 운전 중, 인접한 주차장을 찾아내 예약을 해야하는 것입니다. 운전 중에는 위에서 서현종님께서 말했다시피, 될 수 있다면 빠르게 예약을 할 수 있는 것이 좋습니다. 따라서, 저도 위의 의견을 반영하여 수정을 하는 것에 찬성합니다.

**Comment by ch33233** [comment]
고객으로서 이 서비스를 사용한다고 한다고 할때, 현종님 말씀대로 주어진 시간이 넉넉하다면, 미리 예약할 시 현재 예약 시스템으로 사용해도 괜찮으나, 길가에서 운전 도중 급하게 주차공간을 찾는다면 예약 기능을 간소화한 빠른 예약 기능은 사용자가 간편하고 빠르게 사용할 수 있다는 점에서 필요할 것 같습니다. 하지만 결제 정보에 대한 건은 현재 서비스나 빠른 예약 기능에나 모두 필요한 기능이라고 생각합니다.

**Comment by Kapurichino** [comment]
그런데, 하나 궁금한 점이 있습니다. 저희가 고객의 입장에서 만든 Problem Statement를 보면, The problem에선 고객이 이 서비스를 사용할 때 고객의 위치 정보를 수집해 그와 인접한 주차장에 예약을 할 수 있게끔 합니다. Scenario도 그에 맞게 가정되었구요. 

그러면, 본문의 2번째 문단에서 집이나 회사에서 예약을 하는 경우는 배제된 사항이 아닌가요? 만약 그렇다면, 빠른 예약 기능을 추가하는것이 아니라, 저희가 사전에 생각한 예약 기능을 현종님의 빠른 예약 기능으로 교체하면 될 것 같습니다. 결제 정보를 사전에 고객이 추가할 수 있는 기능을 넣어, 예약을 하는 단계에서의 추가적인 시간 소모를 줄이는 방법을 Scenario 상에 추가하면 되지 않을까요? 결제 정보를 추가하지 않은 고객은 예약 단계에서 정보를 입력하게 하고요 :)

**Comment by SeoHyunJong** [comment]
지금의 예약 기능을 수정해서 대체하는 것도 괜찮은 것 같습니다. :) 다만, 고객의 위치 정보를 기반으로 하여 인접한 주차장을 찾는 것은 논의가 더 필요한 것 같습니다. 정현님께서 댓글로 달아주신 것처럼 몇가지 우려사항이 있습니다.
결제 정보는 찬혁님과 성원님이 말씀해주신 것처럼 어떠한 예약 기능을 넣더라도 사전에 정보를 받아, 매 예약마다 불필요한 재입력을 방지해야 할 것 같습니다. :)
또 생각해보니 빠른 예약에도 장점이 있지만, 기존의 예약 방식인 slot을 선택하는 것도 어느 정도 장점이 있는 것 같습니다.
고객이 원하는 자리를 직접 고를 수 있다는 이점이 있습니다. 다만, 고객의 요구사항에서 slot 선택이 우선순위에 있는 지는  좀 더 생각해봐야겠습니다. :)

**Comment by ddis1004** [comment]
디스코드로 토의했을 때는 "주인이 다른 여러 주차장이 서비스에 등록되려면 주차장 주인을 위한 서비스도 제공을 해야한다. 너무 복잡해지는 것을 막기위해 주차장 하나의 주인이 개발을 요청했다고 가정하자." 라고 정했습니다.
인접한 주차장이 예약되는 것이 아니기 때문에 집이나 회사에서 예약할때 생기는 문제는 없을 것 같습니다.

그와 별개로 예약 자동화는 좋고 추가할만한 기능이라고 생각합니다.
slot을 선택하는 것도 이점이 있으니 시간을 입력하면 slot이 자동으로 선택되지만, 고객이 다른 slot을 원한다면 별도의 과정을 통해 바꿀 수 있도록 하는 것은 어떨까요?

**Comment by SeoHyunJong** [comment]
서형님의 의견에 보태어 기존의 예약 기능(내부 구성도)에 시간을 먼저 정하면 해당 시간에 비어있는 slot들을 보여주는 기능을 추가하면 좋을 것 같습니다. :) 슬롯 선택 후 시간 선택 기능도 있는 것이고, 시간 선택 후 빈 슬롯 선택하는 기능도 있는 것이죠.

**Comment by ch33233** [comment]
위에 말하셨던 예약 자동화 기능 중 한 부분인, 빠른 예약 기능에서 예약 시간을 선택하면 자동으로 빈 slot을 지정해 주는 것은 좋습니다. 일반 예약 기능에서 예약 시간 선택 후 주차할 slot을 선택하는 것까지도 좋아보입니다. 하지만 주차장 내 빈 slot을 선택한 다음에 예약 시간을 선택하는 기능이 필요할까요?

**Comment by SeoHyunJong** [comment]
음 생각해보니 그닥 필요하지 않을것 같습니다. 시간이 넘쳐나고 자신은 특정 자리 아니면 안된다 하는 고객은 많지 않을테니까요. :)
